force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Candidates.recordType-meta.xml
<RecordType>
    <fullName>Candidates</fullName>
    <active>true</active>
    <description>User for tracking Candidate information in the recruiting application</description>
    <label>Candidates</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>User for normal Business Contacts</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$User.isHiringManager__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/recruitingDataFactory.cls
@isTest
public class recruitingDataFactory {

/*
Method to creste one or more positions .... return as a list
Status options - New, Open, Closed - create based on passed parameter
OPen Positions must have a Description
??What about hiring manager??
*/
//Scenario Setup Methods
public static void createSimpleInterviewScenario(String type){
    if(type=='Single'){
        List<Position__c> newPos = createPositions('Open',1);
        insert newPos;

        List<Application__c> newApps = createApplications(1,newPos);
        insert newApps;       
    }
    else if(type=='Bulk'){
        List<Position__c> newPos = createPositions('Open',201);
        insert newPos;

        List<Application__c> newApps = createApplications(1,newPos);
        insert newApps;      
    }
}

//TODO? Create method to return appliocable user based on requested persona

//Builder Methods
public static List<Position__c> createPositions(String status, Integer createNum){
    List<Position__c> newPositions = new List<Position__c>();  
    Set<String> validStatus = new Set<String>{'New','Open','Closed'};
    if(validStatus.contains(status)){
    //Retrieving user record ID to use for hiring manager
    User hMan = [SELECT ID FROM User WHERE Profile.Name='System Administrator' LIMIT 1];
    for(Integer i=0; i < createNum; i++){
        Position__c newPosition = new Position__c();
            newPosition.Name = 'Test Position #'+String.valueOf(i);
            newPosition.Hiring_Manager__c = hMan.Id;
            newPosition.Description__c = 'Description of position';
            newPosition.Due_Date__c = Date.Today()+90;
            newPosition.Status__c = status;
        newPositions.add(newPosition);
    }
}
    else {
        System.Debug('Invalid status was passed to createPositions method');
    }

    return newPositions;
}
/*
Method to create multiple applications for a position - return as a list
Will need to create contacts for each application and place them under an Account umbrella
For now, all applciations will be in the Applied status
*/
public static List<Application__c> createApplications(Integer createNum, List<Position__c> positions){
    //Assumes that positions have already been inserted
    //Create same number of contacts as createNum and then link them to all positions
    Account umbrellaAccount = new Account(Name='Umbrella Account');
    insert umbrellaAccount; 

    //Need to get correct RecordType Id for Candidates
    RecordType canRT = [SELECT ID FROM RecordType WHERE Name = 'Candidates' LIMIT 1];
    
   
    //Create contacts (candidates) linked to umbrella account and use Candidate recordtype
    List<Contact> newCan = new List<Contact>();
    for(Integer i=0; i < createNum; i++){
        Contact newContact = new Contact();
            newContact.FirstName = 'Test';
            newContact.LastName = 'Candidate#'+String.valueOf(i);
            newContact.AccountId = umbrellaAccount.Id;
            newContact.RecordTypeId = canRT.Id;
        newCan.add(newContact);
    }
    insert newCan;

    List<Application__c> newApps = new List<Application__c>();
    for(Position__c p : positions){
        for(Contact c : newCan){
            Application__c newApp = new Application__c();
                newApp.Name = 'New App';
                newApp.Candidate__c = c.Id;
                newApp.Position__c = p.Id;
                newApp.Status__c = 'Applied';
            newApps.add(newApp);
        }
    }

    return newApps;
}

/*
Method to create interviewers linked to the provided position
*/
public static Interviewer__c createInterviewer(Id positionId, Id userId){
    Interviewer__c newInt = new Interviewer__c();
        newInt.Name = 'New Test Interviewer';
        newInt.Interviewer__c = userId;
        newInt.Position__c = positionId;
    return newInt;
}

/*
Method to create or update reviews linked to the provided position
This for scenarios after interviewing stage has been completed
*/

}