force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewerHandlerTest.cls
@isTest
private class InterviewerHandlerTest {

    // Make a test with no Application


    // Make a test with no position


        /*As a recruiter, when I attach an interviewer to a specific position, I need review records to be generated for each applicant in the interviewing stage so that the designated interviewer can see who they need to meet with. 
      Trigger on Interviewer object*/
      @isTest
      private static void testNewInterviewerInsert_Positive(){
        //Need an application on a position set to Interviewing
        recruitingDataFactory.createSimpleInterviewScenario('Single');
        Application__c currentApp = [SELECT Id, Position__c, Status__c FROM Application__c LIMIT 1];
        currentApp.Status__c = 'Interviewing';
        update currentApp;

        User newIntUser = [SELECT ID FROM User WHERE Profile.Name='Standard Platform User' LIMIT 1];

        Test.startTest();
        //Add an interviewer
        Interviewer__c newInt = recruitingDataFactory.createInterviewer(currentApp.Position__c, newIntUser.Id);
        insert newInt;
        Test.stopTest();

        //Check to see that a review record has been created for the application
        List<Review__c> newRev = [SELECT ID, Application__c, Interviewer__c FROM Review__c];
        System.assertEquals(1, newRev.size(), 'Incorrect number of review records created');
        for(Review__c r: newRev){
            System.assertEquals(currentApp.Id, r.Application__c, 'Review record created but not linked to Application');
            System.assertEquals(newInt.Id, r.Interviewer__c, 'Review record created but not linked to Application');
        }

      }
      @isTest
      private static void testNewInterviewerInsert_Negative(){
         //Need an application on a position set to Interviewing
         recruitingDataFactory.createSimpleInterviewScenario('Single');
         Application__c currentApp = [SELECT Id, Position__c, Status__c FROM Application__c LIMIT 1];
 
         User newIntUser = [SELECT ID FROM User WHERE Profile.Name='Standard Platform User' LIMIT 1];
 
         Test.startTest();
         //Add an interviewer
         Interviewer__c newInt = recruitingDataFactory.createInterviewer(currentApp.Position__c, newIntUser.Id);
         insert newInt;
         Test.stopTest();
 
         //Check to see that a review record has been created for the application
         List<Review__c> newRev = [SELECT ID, Application__c, Interviewer__c FROM Review__c];
         System.assertEquals(0, newRev.size(), 'Incorrect number of review records created');
      }
      @isTest
      private static void testNewInterviewerInsertBulk_Positive(){
        //Need an application on a position set to Interviewing
        List<Position__c> newPos = recruitingDataFactory.createPositions('Open',1);
        insert newPos;
        List<Application__c> newApps = recruitingDataFactory.createApplications(201,newPos);
        insert newApps;
        for (Application__c a : newApps){
            a.Status__c = 'Interviewing';
        }
        update newApps;
        User newIntUser = [SELECT ID FROM User WHERE Profile.Name='Standard Platform User' LIMIT 1];

        Test.startTest();
        //Add an interviewer
        Interviewer__c newInt = recruitingDataFactory.createInterviewer(newPos[0].Id, newIntUser.Id);
        insert newInt;
        Test.stopTest();

        //Check to see that a review record has been created for the application
        List<Review__c> newRev = [SELECT ID, Application__c, Interviewer__c FROM Review__c];
        System.assertEquals(201, newRev.size(), 'Incorrect number of review records created');
        Set<Id> appIds = new Set<Id>();
        for(Review__c r: newRev){
            appIds.add(r.Application__c);
            System.assertEquals(newInt.Id, r.Interviewer__c, 'Review record created but not linked to Application');
        }
        System.assertEquals(201, appids.size(), 'Incomplete linking of review records to applications');
      }

    
}