force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Candidates.recordType-meta.xml
<RecordType>
    <fullName>Candidates</fullName>
    <active>true</active>
    <description>User for tracking Candidate information in the recruiting application</description>
    <label>Candidates</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>User for normal Business Contacts</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PositionDetailController.cls
public class PositionDetailController {
    private Position__c position;

    public String firstName {get; set;}
    public String lastName {get;set;}
    public String email {get;set;}

    public PositionDetailController(ApexPages.StandardController controller) {
        this.position = (Position__c)controller.getRecord();
    }
    
    public PageReference apply() {
        // Find umbrella account
        Account a = [SELECT ID FROM Account WHERE Name = 'Account to store All Candidates' LIMIT 1];
        //Create Contact
        Contact newCandidate = new Contact();
            newCandidate.FirstName = firstName;
            newCandidate.LastName = lastName;
            newCandidate.Email = email;
            newCandidate.AccountId = a.Id;
        insert newCandidate;

        //Create application
        Application__c newApp = new Application__c();
            newApp.Position__c = position.Id;
            newApp.Candidate__c = newCandidate.Id;
        insert newApp;

        return new PageReference('/apex/availablePositions');
    }
}