force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationHandlerTest.cls
@isTest
private class ApplicationHandlerTest {
    
    @isTest
    private static void testApplicationUpdate_Positive(){
      //Need an application on a position set to Interviewing
      recruitingDataFactory.createSimpleInterviewScenario('Single');
      
       //Keep in mind that there should be an interviewer records automatically created for the Hiring Manager

      Test.startTest();
      Application__c currentApp = [SELECT Id, Position__c, Status__c FROM Application__c LIMIT 1];
      currentApp.Status__c = 'Interviewing';
      update currentApp;
      Test.stopTest();

      //Check to see that 2 review records have been created for the application
      List<Review__c> newRev = [SELECT ID, Application__c, Interviewer__c FROM Review__c];
      System.assertEquals(1, newRev.size(), 'Incorrect number of review records created');

    }
    @isTest
    private static void testApplicationUpdate_Negative(){
       //Need an application on a position set to Interviewing
       recruitingDataFactory.createSimpleInterviewScenario('Single');
 
          //Keep in mind that there should be an interviewer records automatically created for the Hiring Manager
 
       Test.startTest();
       Application__c currentApp = [SELECT Id, Position__c, Status__c FROM Application__c LIMIT 1];
       currentApp.Status__c = 'Rejected';
       update currentApp;
       Test.stopTest();
 
       //Check to see that 2 review records have been created for the application
       List<Review__c> newRev = [SELECT ID, Application__c, Interviewer__c FROM Review__c];
       System.assertEquals(0, newRev.size(), 'Incorrect number of review records created');
 
    }
    @isTest
    private static void testApplicationUpdateBulk_Positive(){
      //Need an application on a position set to Interviewing
      recruitingDataFactory.createSimpleInterviewScenario('Bulk');


       //Keep in mind that there should be an interviewer records automatically created for the Hiring Manager

      Test.startTest();
      List<Application__c> currentApps = [SELECT Id, Position__c, Status__c FROM Application__c];
      for (Application__c app : currentApps){
        app.Status__c = 'Interviewing';
      }
            update currentApps;
      Test.stopTest();

      //Check to see that 1 review record for each applciation have been created Total of 201
      List<Review__c> newRev = [SELECT ID, Application__c, Interviewer__c FROM Review__c];
      System.assertEquals(201, newRev.size(), 'Incorrect number of review records created');
    }

}