force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewerHandler.cls
public class InterviewerHandler {
    // Constants 
    static final String APP_STATUS_INTERVIEWING = 'Interviewing';
    
    // When Interviewer is Attached to a Position Create a BLANK Review Record if Application Status = 'Interviewing'
    public static void createReviewRecord(List<Interviewer__c> intListNew){

        // Get the Position Ids from the Interview trigger.New List
        Set<Id> posIds = new Set<Id>();
        for(Interviewer__c i : intListNew){
            posIds.add(i.Position__c);
        }

        // Get the Application List
        List<Application__c> appList = [SELECT Id, Status__c, Position__c 
                                            FROM Application__c 
                                            WHERE Position__c IN :posIds 
                                            AND Status__c =: APP_STATUS_INTERVIEWING];

        // Call Utility to build the Review Records
        List<Review__c> revList = MainReviewUtility.makeRecordsAfterDupCheck(intListNew, appList);
        insert revList;
 
    } // End of createReviewRecord

    // Teacher version
    public static void createReviewFromInterviewInsert(List<Interviewer__c> triggernew){
        // Determine associated positions
        Set<Id> posIds = new Set<Id>();
        for(Interviewer__c inv: triggernew){
            posIds.add(inv.Position__c);
        }

        // Get the Application List
        List<Application__c> intApps = new List<Application__c>();
        for(Position__c p : [SELECT Id, (SELECT Id, Status__c, Position__c FROM Applications__r) FROM Position__c WHERE Id IN: posIds]){
            for(Application__c app: p.Applications__r){
                if(app.Status__c == 'Interviewing'){
                    intApps.add(app);
                }
            }
        }

        // Create review Records for those applications linked to the new interviewer
        List<Review__c> newRevs = new List<Review__c>();
        for(Interviewer__c invCheck : triggernew){
            for(Application__c app : intApps){
                if(app.Position__c == invCheck.Position__c){
                    Review__c rev = new Review__c();
                    rev.Interviewer__c = invCheck.Id;
                    rev.Application__c = app.Id;
                    newRevs.add(rev);
                }
            }
        }
        insert newRevs;
    }
}