force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Candidates.recordType-meta.xml
<RecordType>
    <fullName>Candidates</fullName>
    <active>true</active>
    <description>User for tracking Candidate information in the recruiting application</description>
    <label>Candidates</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>User for normal Business Contacts</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$User.isHiringManager__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/isHiringManager__c.field-meta.xml
<CustomField>
    <fullName>isHiringManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isHiringManager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static Account createSingleAcc() {
        Account acc = new Account();
            acc.name = 'Test Account' + System.Today();
        return acc;
    }

    public static List<Account> createAcc(Integer num) {
        List<Account> accList = new List<Account>();
        for(Integer i = 0; i < num; i++){
            Account acc = new Account();
            acc.name = 'Test Account' + i;
            accList.add(acc);
        }
        return accList;
    }

    public static Opportunity createOpp(Account acc) {
        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test Opp';
        testOpp.StageName = 'Prospecting';
        testOpp.CloseDate = System.Today() + 30;
        testOpp.Type = 'New Customer';
        testOpp.Amount = 112334.31;
        testOpp.AccountId = acc.Id;

        return testOpp;
    }

    public static Opportunity createOppWithParams(Account acc, String name, String stageName, Date closeDate, String type, Decimal amt) {
        Opportunity testOpp = new Opportunity();
        testOpp.Name = name;
        testOpp.StageName = stageName;
        testOpp.CloseDate = closeDate;
        testOpp.Type = type;
        testOpp.Amount = amt;
        testOpp.AccountId = acc.Id;

        return testOpp;
    }

    public static Account createSingleAccountWithOpp(){
        Account a = createSingleAcc();
        insert a;

        Opportunity o = createOpp(a);
        insert o;

        return a;
    }

    // Test Data for Recruiting App

    public static User createUser(Boolean isHiringManager){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'GenWatt Recruiting'];
        String random = generateRandomString(6);
        User u = new User();
        u.LastName = 'Tester';
        u.Alias = 'TesterUser';
        u.Email = 'TesterUser' + random + '@yopmail.com';
        u.Username = u.Email;
        u.CommunityNickname = 'TesterUser';
        u.ProfileId  = p.Id;
        u.IsActive = true;
        u.TimeZoneSidKey='America/New_York';
        u.LanguageLocaleKey='en_US';
        u.EmailEncodingKey='UTF-8';
        u.isHiringManager__c = isHiringManager;
        return u;
    }

    public static List<Position__c> createPositions(Integer num, User hiringManager, List<String> status){
        List<Position__c> posList = new List<Position__c>();
        if(status.size() != num){
            for(Integer i = (num-status.size()); i <= num; i++){
                status.add('New');
            }
        }

        for(Integer i = 0; i < num; i++){
            Position__c pos = new Position__c();
            pos.Description__c = 'A new exciting test position!';
            pos.Due_Date__c = System.TODAY() + 91;
            pos.Hiring_Manager__c = hiringManager.Id;
            pos.Name = 'Head Test User';
            pos.Salary__c = 95000;
            pos.Status__c = status[i];
            posList.add(pos);
        }

        return posList;
    }

    public static List<Contact> createCandidates(Integer num){
        List<Contact> candidateList = new List<Contact>();

        RecordType recrdType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Candidates'];
        Account acc = createSingleAcc();
        insert acc;

        for(Integer i = 0; i < num; i++){
            Contact c = new Contact();
            c.RecordType = recrdType;
            c.FirstName ='Candidate';
            c.LastName = 'Tester';
            c.AccountId = acc.Id;
            String random = generateRandomString(6);
            c.Email = 'Candidatetester' + random + '@yopmail.com';
            c.Phone = '123-456-7890';
            candidateList.add(c);
        }

        return candidateList;
    }

    public static List<Application__c> createApplications(Integer num, List<Contact> candidates, List<Position__c> positions){
        List<Application__c> appList = new List<Application__c>();

        for(Integer i = 0; i < num; i++){
            Application__c app = new Application__c();
            app.Name = 'Test App 1';
            app.Candidate__c = candidates[i].Id;
            app.Position__c = positions[i].Id;
            appList.add(app);
        }

        return appList;

    }

    public static List<Interviewer__c> createInterviewers(List<Application__c> appList, List<User> uList, List<Position__c> posList){
        List<Interviewer__c> intList = new List<Interviewer__c>();
        // Check that Application List is smaller or equal to User List

        for(Integer i = 0; i < appList.size(); i++){
            Interviewer__c intv = new Interviewer__c();
            if(uList[i].Id == NULL){
                intv.Interviewer__c = UserInfo.getUserId();
            } else {
                intv.Interviewer__c = uList[i].Id;
            }
            intv.Name = 'Test Interviewer ' + System.TODAY();
            intv.Position__c = posList[i].Id;
            intList.add(intv);
        }
        return intList;
    }

    public static List<Review__c> createReviews(List<Application__c> appList, List<Interviewer__c> intList){
        List<Review__c> rewList = new List<Review__c>();

        for(Integer i = 0; i <= appList.size(); i++){
            Review__c rev = new Review__c();
            rev.Application__c = appList[i].Id;
            rev.Interviewer__c = intList[i].Id;
            rev.Name = 'Test Review ' + System.TODAY();
            rewList.add(rev);
        }

        return rewList;
    }
    
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
           Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }

}